[package]
name = "AdventOfCode2020"
version = "0.1.0"
authors = ["chuck <chuck-bates@pluralsight.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name="day-1-1"
test=false
bench=false

[dependencies]
